# -*- coding: utf-8 -*-
"""Mindrove_BiLSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1osHie23D0dTlF-NpSD5j9tK9GQWwZwb8
"""

import pandas as pd
import numpy as np
from scipy import signal
import torch
import torch.nn as nn
import glob
import os
import sys
from torch.utils.data import DataLoader, TensorDataset
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
# from google.colab import drive
# from IPython.display import display
import matplotlib.pyplot as plt
import seaborn as sns

# --- 1. MOUNT DRIVE & SETUP ---
# drive.mount('/content/drive')
# base_path = '/content/drive/MyDrive/Neurotech/'
base_path = os.path.dirname(os.path.abspath(__file__))


# # --- 2. DATA EXTRACTION ---
# print("Extracting datasets...")
# uci_zip = os.path.join(base_path, 'emg_gestures.zip')
# mindrove_zip = os.path.join(base_path, 'mindrove_txt.zip')

# !rm -rf uci_data mindrove_data uci_temp
# if os.path.exists(uci_zip):
#     !unzip -o -q "{uci_zip}" -d /content/uci_temp
#     !mkdir -p /content/uci_data
#     !cp -r /content/uci_temp/* /content/uci_data/ 2>/dev/null || :
# if os.path.exists(mindrove_zip):
#     !mkdir -p /content/mindrove_data
#     !unzip -o -q "{mindrove_zip}" -d /content/mindrove_data

# --- 3. CORE FUNCTIONS---

def filter_emg_data(data, fs=1000.0):
    notch_freq = 60.0
    Q = 30.0
    # Safety check for low sample rates
    if notch_freq >= (fs / 2): return data

    b_notch, a_notch = signal.iirnotch(notch_freq, Q, fs)
    sos_notch = signal.tf2sos(b_notch, a_notch)
    sos_band = signal.butter(4, [10.0, min(200.0, (fs/2)-1)], btype='band', fs=fs, output='sos')

    filtered_data = np.zeros_like(data)
    for ch in range(data.shape[1]):
        ch_data = signal.sosfiltfilt(sos_notch, data[:, ch])
        ch_data = signal.sosfiltfilt(sos_band, ch_data)
        filtered_data[:, ch] = ch_data
    return filtered_data

def create_sequences(df, window_size, step):
    if df.empty: return torch.tensor([]), torch.tensor([])
    df = df.dropna(subset=['Class'])
    channels = ['CH1', 'CH2', 'CH3', 'CH4']
    data = df[channels].values
    labels = df['Class'].values.astype(int)

    X, y = [], []
    for i in range(0, len(data) - window_size, step):
        window_labels = labels[i:i+window_size]
        if np.all(window_labels == window_labels[0]):
            X.append(data[i:i+window_size])
            y.append(window_labels[0])
    if not X: return torch.tensor([]), torch.tensor([])
    return torch.tensor(np.array(X), dtype=torch.float32), torch.tensor(y, dtype=torch.long)

# --- 4. DATA LOADERS ---

def load_continuous_60hz_custom_filter(file_path, fs=60.0):
    """Loads RAW channels and applies YOUR custom filter."""
    print(f"Processing RAW 60Hz file: {os.path.basename(file_path)}")
    df = pd.read_csv(file_path, sep='\t')
    raw_cols = ['Channel1', 'Channel2', 'Channel3', 'Channel4']
    emg_raw = df[raw_cols].values

    # Apply custom filter
    emg_filtered = filter_emg_data(emg_raw, fs=fs)
    df_emg = pd.DataFrame(emg_filtered, columns=['CH1', 'CH2', 'CH3', 'CH4'])

    # Labeling intervals (Relax, Fist, Rock, Peace, Shaka)
    intervals = [(0,10,0), (10,30,1), (30,40,0), (40,60,2), (60,70,0), (70,90,3), (90,100,0), (100,120,4)]
    df_emg['Class'] = -1
    for s, e, l in intervals:
        s_idx, e_idx = int(s*fs), int(e*fs)
        if s_idx < len(df_emg):
            df_emg.iloc[s_idx:min(e_idx, len(df_emg)), df_emg.columns.get_loc('Class')] = l

    df_emg = df_emg[df_emg['Class'] != -1].copy()
    scaler = StandardScaler()
    df_emg[['CH1', 'CH2', 'CH3', 'CH4']] = scaler.fit_transform(df_emg[['CH1', 'CH2', 'CH3', 'CH4']])
    return df_emg

# def load_uci_4ch(path):
#     all_data = []
#     files = glob.glob(os.path.join(path, '**', '*.txt'), recursive=True)
#     for f in files:
#         if 'README' in f: continue
#         try:
#             df = pd.read_csv(f, sep='\t', header='infer', low_memory=False, on_bad_lines='skip')
#             if df.shape[1] < 10: continue
#             df = df.iloc[:, [2, 4, 6, 8, 9]]
#             df.columns = ['CH1', 'CH2', 'CH3', 'CH4', 'Class']
#             for col in df.columns: df[col] = pd.to_numeric(df[col], errors='coerce')
#             df = df.dropna()
#             df = df[df['Class'] > 0].copy()
#             df['Class'] = (df['Class'] - 1).astype(int)
#             all_data.append(df)
#         except: continue
#     if not all_data: return pd.DataFrame()
#     full_df = pd.concat(all_data, ignore_index=True)
#     scaler = StandardScaler()
#     full_df[['CH1', 'CH2', 'CH3', 'CH4']] = scaler.fit_transform(full_df[['CH1', 'CH2', 'CH3', 'CH4']])
#     return full_df

# def load_all_subjects(path):
#     subject_datasets = {}
#     for i in range(1, 9):
#         sub_label = f"subject {i}"
#         all_data = []
#         search_pattern = os.path.join(path, '**', sub_label, '[0-4].txt')
#         files = glob.glob(search_pattern, recursive=True)
#         if not files: continue
#         print(f"Loading {sub_label}...")
#         for f in files:
#             try:
#                 gid = int(os.path.basename(f).replace('.txt', ''))
#                 df = pd.read_csv(f, header=None, sep=None, engine='python').iloc[:, :4]
#                 df.columns = ['CH1', 'CH2', 'CH3', 'CH4']
#                 df[['CH1', 'CH2', 'CH3', 'CH4']] = filter_emg_data(df.values, fs=500.0)
#                 df['Class'] = gid
#                 all_data.append(df)
#             except: continue
#         if all_data:
#             full_df = pd.concat(all_data, ignore_index=True)
#             scaler = StandardScaler()
#             full_df[['CH1', 'CH2', 'CH3', 'CH4']] = scaler.fit_transform(full_df[['CH1', 'CH2', 'CH3', 'CH4']])
#             subject_datasets[sub_label] = full_df
#     return subject_datasets

# --- 5. MODEL & TRAINER ---

class FinalPushLSTM(nn.Module):
    def __init__(self, input_size=4, hidden_size=128, num_layers=2, num_classes=4):
        super().__init__()
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True, dropout=0.4, bidirectional=True)
        self.fc = nn.Sequential(
            nn.Linear(hidden_size * 2, 256), nn.BatchNorm1d(256), nn.ReLU(),
            nn.Dropout(0.5), nn.Linear(256, num_classes)
        )
    def forward(self, x):
        self.lstm.flatten_parameters()
        out, _ = self.lstm(x)
        return self.fc(out[:, -1, :])

def run_experiment(X, y, name):
    # device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    device = torch.device("mps" if torch.backends.mps.is_available() else "cuda" if torch.cuda.is_available() else "cpu")
    X_np, y_np = X.cpu().numpy(), y.cpu().numpy()
    X_train, X_val, y_train, y_val = train_test_split(X_np, y_np, test_size=0.2, random_state=42, stratify=y_np)

    train_loader = DataLoader(TensorDataset(torch.tensor(X_train), torch.tensor(y_train)), batch_size=256, shuffle=True)
    val_loader = DataLoader(TensorDataset(torch.tensor(X_val), torch.tensor(y_val)), batch_size=256)

    model = FinalPushLSTM(num_classes=int(y_np.max() + 1)).to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=0.001, weight_decay=0.01)
    criterion = nn.CrossEntropyLoss(label_smoothing=0.1)
    scheduler = torch.optim.lr_scheduler.OneCycleLR(optimizer, max_lr=0.003, steps_per_epoch=len(train_loader), epochs=15)

    history = {'train_loss': [], 'train_acc': [], 'val_loss': [], 'val_acc': [], 'lrs': []}
    print(f"\n{'='*20} Starting Training: {name} {'='*20}")

    for epoch in range(15):
        model.train()
        t_loss, t_corr, t_total = 0, 0, 0
        for bx, by in train_loader:
            bx, by = bx.to(device), by.to(device)
            optimizer.zero_grad(); outputs = model(bx); loss = criterion(outputs, by); loss.backward(); optimizer.step()
            history['lrs'].append(optimizer.param_groups[0]['lr']); scheduler.step()
            t_loss += loss.item(); t_corr += (outputs.argmax(1) == by).sum().item(); t_total += by.size(0)

        model.eval()
        v_loss, v_corr, v_total = 0, 0, 0
        with torch.no_grad():
            for vx, vy in val_loader:
                vx, vy = vx.to(device), vy.to(device)
                v_out = model(vx); v_loss += criterion(v_out, vy).item()
                v_corr += (v_out.argmax(1) == vy).sum().item(); v_total += vy.size(0)

        history['train_loss'].append(t_loss/len(train_loader)); history['train_acc'].append((t_corr/t_total)*100)
        history['val_loss'].append(v_loss/len(val_loader)); history['val_acc'].append((v_corr/v_total)*100)
        print(f"Epoch {epoch+1:02d} | T-Loss: {history['train_loss'][-1]:.3f} | V-Acc: {history['val_acc'][-1]:.2f}%")

    # --- VISUALIZATION ---
    plt.figure(figsize=(18, 5))
    plt.subplot(1, 3, 1); plt.plot(history['train_loss'], label='Train'); plt.plot(history['val_loss'], label='Val'); plt.title('Loss'); plt.legend()
    plt.subplot(1, 3, 2); plt.plot(history['train_acc'], label='Train'); plt.plot(history['val_acc'], label='Val'); plt.title('Accuracy'); plt.legend()
    plt.subplot(1, 3, 3); plt.plot(history['lrs']); plt.title('OneCycle LR')
    plt.tight_layout(); plt.show()

    plt.figure(figsize=(8, 6))
    cm = confusion_matrix(y_val, model(torch.tensor(X_val).to(device)).argmax(1).cpu().numpy())
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues'); plt.title(f'CM: {name}'); plt.show()
    return history['val_acc'][-1]

# --- 6. EXECUTION ---
summary_report = {}

# 1. New 60Hz Recording (Custom Filter)
csv_60hz = os.path.join(base_path, 'EMG_Mindrove_60hz_20sec.csv')
if os.path.exists(csv_60hz):
    df_60 = load_continuous_60hz_custom_filter(csv_60hz)
    Xc, yc = create_sequences(df_60, window_size=15, step=5)
    summary_report["Continuous_60Hz"] = run_experiment(Xc, yc, "60Hz_New_Dataset")

# 2. Original Mindrove Subjects
# all_subjects_data = load_all_subjects('/content/mindrove_data')
# for sub_name, df in all_subjects_data.items():
#     X, y = create_sequences(df, window_size=50, step=10)
#     summary_report[sub_name] = run_experiment(X, y, sub_name)

# # 3. UCI Dataset
# df_u = load_uci_4ch('/content/uci_data')
# if not df_u.empty:
#     Xu, yu = create_sequences(df_u, window_size=100, step=20)
#     summary_report["UCI"] = run_experiment(Xu, yu, "UCI_Static_Dataset")

# --- FINAL SUMMARY TABLE ---
print("\n" + "="*40)
print(f"{'EXPERIMENT':<20} | {'ACCURACY':<10}")
print("-" * 40)
for exp_name, final_acc in summary_report.items():
    print(f"{exp_name:<20} | {final_acc:.2f}%")
print("="*40)